//
//  BuildInfo.swift
//  Cosmo Trader
//
//  Provides version and build information for the app.
//  Build metadata is generated by increment_build.sh during the build process.
//
//  USAGE:
//  ------
//  let version = BuildInfo.version           // "1.0"
//  let build = BuildInfo.build               // "42"
//  let full = BuildInfo.fullVersion          // "1.0 (42)"
//  let timestamp = BuildInfo.buildTimestamp  // "2024-01-15 10:30:00"

import Foundation
import UIKit

// MARK: - Build Information

/// Provides version, build, and metadata information for the app
enum BuildInfo {

    // MARK: - Version Info (from Info.plist)

    /// Marketing version (CFBundleShortVersionString) e.g., "1.0"
    static var version: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "0.0"
    }

    /// Build number (CFBundleVersion) e.g., "42"
    static var build: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? "0"
    }

    /// Full version string e.g., "1.0 (42)"
    static var fullVersion: String {
        "\(version) (\(build))"
    }

    /// Version for display e.g., "v1.0"
    static var displayVersion: String {
        "v\(version)"
    }

    // MARK: - App Info

    /// App name
    static var appName: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleName") as? String ?? "Cosmo Trader"
    }

    /// Bundle identifier
    static var bundleIdentifier: String {
        Bundle.main.bundleIdentifier ?? "com.cosmotrader.app"
    }

    // MARK: - Environment

    /// Current environment from AppEnvironment
    static var environment: AppEnvironment {
        AppEnvironment.current
    }

    /// Whether this is a debug build
    static var isDebug: Bool {
        #if DEBUG
        return true
        #else
        return false
        #endif
    }

    /// Whether this is a release build
    static var isRelease: Bool {
        !isDebug
    }

    /// Whether this is a TestFlight build
    static var isTestFlight: Bool {
        Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt"
    }

    /// Whether this is an App Store build
    static var isAppStore: Bool {
        isRelease && !isTestFlight
    }

    // MARK: - Device Info

    /// Device model identifier
    static var deviceModel: String {
        #if targetEnvironment(simulator)
        return "Simulator"
        #else
        var systemInfo = utsname()
        uname(&systemInfo)
        let machineMirror = Mirror(reflecting: systemInfo.machine)
        let identifier = machineMirror.children.reduce("") { identifier, element in
            guard let value = element.value as? Int8, value != 0 else { return identifier }
            return identifier + String(UnicodeScalar(UInt8(value)))
        }
        return identifier
        #endif
    }

    /// iOS version
    static var osVersion: String {
        let version = ProcessInfo.processInfo.operatingSystemVersion
        return "\(version.majorVersion).\(version.minorVersion).\(version.patchVersion)"
    }

    /// Device name (e.g., "iPhone 15 Pro")
    static var deviceName: String {
        UIDevice.current.name
    }

    // MARK: - Formatted Strings

    /// Full build info string for debug display
    static var debugInfoString: String {
        var lines: [String] = []
        lines.append("Version: \(fullVersion)")
        lines.append("Environment: \(environment.rawValue)")
        lines.append("Build Config: \(isDebug ? "Debug" : "Release")")

        // Add generated build info if available
        let timestamp = buildTimestamp
        if !timestamp.isEmpty {
            lines.append("Built: \(timestamp)")
        }
        let commit = gitCommit
        if !commit.isEmpty && commit != "unknown" {
            lines.append("Git: \(gitBranch)@\(commit)")
        }

        lines.append("Device: \(deviceModel)")
        lines.append("iOS: \(osVersion)")

        return lines.joined(separator: "\n")
    }

    /// Short version info for crash reports
    static var crashReportInfo: String {
        "\(fullVersion) [\(environment.rawValue)] \(deviceModel) iOS \(osVersion)"
    }

    /// User agent string for API requests
    static var userAgent: String {
        "\(appName)/\(version) (Build \(build); iOS \(osVersion); \(deviceModel))"
    }
}

// MARK: - Build Metadata Access
// Note: These values are defined in BuildInfo.generated.swift
// which is created by increment_build.sh during the build process

// MARK: - Version Comparison

extension BuildInfo {

    /// Parse version string into components
    static func parseVersion(_ version: String) -> (major: Int, minor: Int, patch: Int) {
        let components = version.split(separator: ".").compactMap { Int($0) }
        return (
            major: components.count > 0 ? components[0] : 0,
            minor: components.count > 1 ? components[1] : 0,
            patch: components.count > 2 ? components[2] : 0
        )
    }

    /// Compare two version strings
    /// Returns: -1 if v1 < v2, 0 if equal, 1 if v1 > v2
    static func compareVersions(_ v1: String, _ v2: String) -> Int {
        let p1 = parseVersion(v1)
        let p2 = parseVersion(v2)

        if p1.major != p2.major { return p1.major < p2.major ? -1 : 1 }
        if p1.minor != p2.minor { return p1.minor < p2.minor ? -1 : 1 }
        if p1.patch != p2.patch { return p1.patch < p2.patch ? -1 : 1 }
        return 0
    }

    /// Check if current version is at least the specified version
    static func isAtLeastVersion(_ minVersion: String) -> Bool {
        compareVersions(version, minVersion) >= 0
    }
}
