#!/bin/bash

# increment_build.sh
# Cosmo Trader
#
# Build phase script that increments build number for Release builds.
# Also generates build metadata with timestamp.
#
# USAGE:
# ------
# Add as a Run Script Build Phase in Xcode:
# 1. Select target → Build Phases → + → New Run Script Phase
# 2. Move it BEFORE "Compile Sources"
# 3. Add: "${SRCROOT}/Scripts/increment_build.sh"
#
# CONFIGURATION:
# --------------
# Set SKIP_BUILD_INCREMENT=1 in Xcode scheme environment to skip
# Set INCREMENT_ON_DEBUG=1 to also increment on Debug builds

set -e

# Configuration
PROJECT_DIR="${SRCROOT}"
PLIST_PATH="${PROJECT_DIR}/Cosmo Trader/Info.plist"
BUILD_INFO_PATH="${PROJECT_DIR}/Cosmo Trader/Configuration/BuildInfo.generated.swift"
PBXPROJ_PATH="${PROJECT_DIR}/Cosmo Trader.xcodeproj/project.pbxproj"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[Build]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[Build]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[Build]${NC} $1"
}

log_error() {
    echo -e "${RED}[Build]${NC} $1"
}

# Check if we should skip increment
if [ "${SKIP_BUILD_INCREMENT}" == "1" ]; then
    log_warning "Skipping build increment (SKIP_BUILD_INCREMENT=1)"
    exit 0
fi

# Check build configuration
SHOULD_INCREMENT=false

if [ "${CONFIGURATION}" == "Release" ]; then
    SHOULD_INCREMENT=true
    log_info "Release build detected - will increment build number"
elif [ "${INCREMENT_ON_DEBUG}" == "1" ]; then
    SHOULD_INCREMENT=true
    log_info "Debug build with INCREMENT_ON_DEBUG=1 - will increment build number"
else
    log_info "Debug build - skipping build number increment"
fi

# Get current version info from project file
CURRENT_BUILD=$(grep -m 1 "CURRENT_PROJECT_VERSION" "${PBXPROJ_PATH}" | sed 's/.*= //' | sed 's/;//')
MARKETING_VERSION=$(grep -m 1 "MARKETING_VERSION" "${PBXPROJ_PATH}" | sed 's/.*= //' | sed 's/;//')

log_info "Current version: ${MARKETING_VERSION} (${CURRENT_BUILD})"

# Generate build timestamp
BUILD_TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
BUILD_TIMESTAMP_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BUILD_DATE=$(date +"%Y-%m-%d")
BUILD_TIME=$(date +"%H:%M:%S")

# Get git info if available
GIT_COMMIT="unknown"
GIT_BRANCH="unknown"
GIT_TAG=""

if command -v git &> /dev/null && [ -d "${PROJECT_DIR}/.git" ]; then
    GIT_COMMIT=$(git -C "${PROJECT_DIR}" rev-parse --short HEAD 2>/dev/null || echo "unknown")
    GIT_BRANCH=$(git -C "${PROJECT_DIR}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    GIT_TAG=$(git -C "${PROJECT_DIR}" describe --tags --exact-match 2>/dev/null || echo "")
fi

# Increment build number if needed
NEW_BUILD=${CURRENT_BUILD}
if [ "${SHOULD_INCREMENT}" == "true" ]; then
    NEW_BUILD=$((CURRENT_BUILD + 1))

    # Update project.pbxproj with new build number
    # Use sed to replace all occurrences of CURRENT_PROJECT_VERSION
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS sed requires empty string for -i
        sed -i '' "s/CURRENT_PROJECT_VERSION = ${CURRENT_BUILD};/CURRENT_PROJECT_VERSION = ${NEW_BUILD};/g" "${PBXPROJ_PATH}"
    else
        # GNU sed
        sed -i "s/CURRENT_PROJECT_VERSION = ${CURRENT_BUILD};/CURRENT_PROJECT_VERSION = ${NEW_BUILD};/g" "${PBXPROJ_PATH}"
    fi

    log_success "Build number incremented: ${CURRENT_BUILD} → ${NEW_BUILD}"
fi

# Create directory for generated file if needed
mkdir -p "$(dirname "${BUILD_INFO_PATH}")"

# Generate BuildInfo.generated.swift
cat > "${BUILD_INFO_PATH}" << EOF
//
//  BuildInfo.generated.swift
//  Cosmo Trader
//
//  AUTO-GENERATED FILE - DO NOT EDIT
//  Generated by increment_build.sh on ${BUILD_TIMESTAMP}
//

import Foundation

// MARK: - Build Metadata (Generated)

extension BuildInfo {

    /// Build timestamp (when this build was created)
    static let buildTimestamp = "${BUILD_TIMESTAMP}"

    /// Build timestamp in ISO 8601 format
    static let buildTimestampISO = "${BUILD_TIMESTAMP_ISO}"

    /// Build date (YYYY-MM-DD)
    static let buildDate = "${BUILD_DATE}"

    /// Build time (HH:MM:SS)
    static let buildTime = "${BUILD_TIME}"

    /// Git commit hash (short)
    static let gitCommit = "${GIT_COMMIT}"

    /// Git branch name
    static let gitBranch = "${GIT_BRANCH}"

    /// Git tag (if this is a tagged release)
    static let gitTag = "${GIT_TAG}"

    /// Build configuration (Debug/Release)
    static let buildConfiguration = "${CONFIGURATION}"

    /// Build number at generation time
    static let generatedBuildNumber = ${NEW_BUILD}
}
EOF

log_success "Generated BuildInfo.generated.swift"
log_info "Build: ${MARKETING_VERSION} (${NEW_BUILD})"
log_info "Timestamp: ${BUILD_TIMESTAMP}"
log_info "Git: ${GIT_BRANCH}@${GIT_COMMIT}"

exit 0
