#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

failures=0

require_absent() {
  local file="$1"
  local needle="$2"
  if grep -Fq "$needle" "$ROOT/$file"; then
    echo "FAIL: '$needle' is still present in $file"
    failures=$((failures + 1))
  fi
}

require_present() {
  local file="$1"
  local needle="$2"
  if ! grep -Fq "$needle" "$ROOT/$file"; then
    echo "FAIL: '$needle' is missing from $file"
    failures=$((failures + 1))
  fi
}

require_file_absent() {
  local file="$1"
  if [[ -e "$ROOT/$file" ]]; then
    echo "FAIL: legacy file should not exist: $file"
    failures=$((failures + 1))
  fi
}

require_absent "Cosmo Trader/Views/Components/StockChartView.swift" "stock.chartData(for:"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "Historical price data unavailable"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "Key statistics unavailable"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "fetchHistoricalPriceResult"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "DataSourceIndicator(provenance: chartProvenance"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "Chart will appear when provider data is available."

require_absent "Cosmo Trader/Views/StockDetailView.swift" "generateMockChartData"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "MiniChartView.sampleData"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "formatted52Week"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "stock.formattedMarketCap"
require_present "Cosmo Trader/Views/StockDetailView.swift" "DataSourceIndicator(provenance: priceProvenance"
require_present "Cosmo Trader/Views/StockDetailView.swift" "Fundamentals such as market cap"

require_absent "Cosmo Trader/Services/ChartPatternService.swift" "MockOHLCGenerator.generate"
require_present "Cosmo Trader/Services/ChartPatternService.swift" "pattern analysis unavailable"

require_absent "Cosmo Trader/Services/IPOService.swift" "MockIPOData"
require_absent "Cosmo Trader/Services/IPOService.swift" "loadMockData"
require_present "Cosmo Trader/Services/IPOService.swift" "dataProvenance"
require_present "Cosmo Trader/Views/IPO/IPOListView.swift" "DataSourceIndicator(provenance: ipoService.dataProvenance"

require_absent "Cosmo Trader/Services/EarningsService.swift" "generateMockEarningsData"
require_absent "Cosmo Trader/Services/EarningsService.swift" "Double.random"
require_present "Cosmo Trader/Services/EarningsService.swift" "dataProvenance"
require_present "Cosmo Trader/Views/Components/EarningsViews.swift" "DataSourceIndicator(provenance: earningsService.dataProvenance"

require_absent "Cosmo Trader/Views/Components/PortfolioChartView.swift" "generatePortfolioData"
require_absent "Cosmo Trader/Views/Components/PortfolioChartView.swift" "generateBenchmarkData"
require_present "Cosmo Trader/Views/Components/PortfolioChartView.swift" "Portfolio performance history unavailable"

require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "simulateWeeklyReturn"
require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "generateMockHistory"
require_present "Cosmo Trader/Services/CosmicMoodService.swift" "Provider-backed market trend unavailable"
require_present "Cosmo Trader/Services/CosmicMoodService.swift" "minimumMarketCoverageForScore"
# CosmicMoodData must publish enough metadata for consumers to refuse to
# quote a cosmic-only score as a market measurement.
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "enum CosmicMoodDisplayMode"
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "marketDataCoverage"
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "var isMarketBacked"
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "Cosmic context only"
# Daily Brief must not leak the partial-astro score as a market reading.
require_present "Cosmo Trader/Services/DailyFinancialReadingService.swift" "cosmic context only"
require_present "Cosmo Trader/Services/DailyFinancialReadingService.swift" "marketBackedScore(from:"
require_present "Cosmo Trader/Services/DailyFinancialReadingService.swift" "marketToneProvenance: mood.provenance"
require_present "Cosmo Trader/Models/DailyFinancialReading.swift" "marketToneProvenance"
require_present "Cosmo Trader/Views/Components/DailyFinancialReadingCockpitView.swift" "marketToneCell"
require_present "Cosmo Trader/Views/Components/DailyFinancialReadingCockpitView.swift" "MARKET TONE (COSMIC)"
# Discover must not quote a cosmic-only mood as a market claim.
require_present "Cosmo Trader/ViewModels/DiscoverViewModel.swift" "mood.isMarketBacked, let value = mood.value"
# Gauge surfaces honest unavailable / cosmic-only states.
require_present "Cosmo Trader/Views/Components/CosmicMoodGauge.swift" "N/A"
require_present "Cosmo Trader/Views/Components/CosmicMoodGauge.swift" "COSMIC ONLY"

require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolioDailyPLProvenance"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "changeCell(for:"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" ".mixed(reason:"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "struct PortfolioIntelligenceSummary"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "providerQuoteCoverage"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "verifiedAstrologyCoverage"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "historyCoverage >= 0.70"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "Unknown-founded holdings stay out of zodiac and element denominators"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolioIntelligenceSection"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "PORTFOLIO INTELLIGENCE"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.intelligenceDashboard"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio intelligence distinguishes stored values from provider quote coverage"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio intelligence excludes unknown-founded holdings from zodiac denominator"
require_absent "Cosmo Trader/Services/PortfolioCompatibilityService.swift" "Consider reducing"
require_absent "Cosmo Trader/Services/PortfolioCompatibilityService.swift" "reduce exposure"
require_present "Cosmo Trader/Views/Components/DataSourceIndicator.swift" "Mixed data"

require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "stocks ?? MockStockData"
require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "FULL MOON: VOLATILITY ELEVATED"
require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "WANING MOON: DE-RISKING WINDOW"
require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "SIGNAL CONFIRMED"
require_present "Cosmo Trader/Services/CosmicTickerService.swift" "MARKET DATA UNAVAILABLE"

require_absent "Cosmo Trader/Views/Components/VolumeLeadersView.swift" "from: MockStockData.knownStocks"
require_present "Cosmo Trader/Views/Components/VolumeLeadersView.swift" "Volume leaders unavailable"

require_absent "Cosmo Trader/Services/DailyBriefService.swift" "let knownStocks = Stock.samples + MockStockData.all"
require_absent "Cosmo Trader/Services/DailyBriefService.swift" "for stock in user.portfolio where abs"
require_present "Cosmo Trader/Services/DailyBriefService.swift" "daily highlights must stay empty"

require_file_absent "Cosmo Trader/Views/Tabs/DailyBriefView.swift"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayMarketHoroscopeSummary"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayPortfolioContext"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayStockContext"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayDataCoverage"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayActivationPrompt"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayDataLabelExplainer"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "tertiaryActionTitle"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "primaryAction"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case setupRequired"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case partialContext"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case insufficientCoverage"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case sampleOnly"
require_present "Cosmo Trader/State/AppState.swift" "enum AppNavigationIntent"
require_present "Cosmo Trader/State/AppState.swift" "func requestNavigation"
require_present "Cosmo Trader/Views/ContentView.swift" "DailyBriefBackendView()"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "TodayMarketHoroscopeView("
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "marketRefreshAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "portfolioSetupAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "portfolioImportAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "watchlistSetupAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "discoverSearchAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.requestNavigation(.portfolioAddHolding)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.requestNavigation(.portfolioImport)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.requestNavigation(.discoverSearch)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "await todayViewModel.load(user: appState.currentUser)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "await todayViewModel.reload(user: appState.currentUser)"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "consumeNavigationIntentIfNeeded"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "showImportPortfolio = true"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "consumeNavigationIntentIfNeeded"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "appState.pendingNavigationIntent == .discoverSearch"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "SearchView()"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "final class TodayMarketHoroscopeViewModel"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "loadPortfolioSummaries"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "loadStockCandidate"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "CorrelationDatasetStore.shared"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "final class TodayMarketHoroscopeComposer"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func compose("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func makePortfolioContext("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func makeStockContext("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "private func makeDataCoverage("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "private func makePrimaryAction("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "FETCH MARKET HISTORY"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "ADD HOLDING"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Add holding manually"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Import portfolio"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "ADD WATCHLIST SYMBOLS"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Add symbol"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Open Discover/Search"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Fetch SPY / QQQ / DIA / IWM history"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Do not create sample market data"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "private func dataLabelExplainers()"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.marketHoroscope\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.oneGlanceRead\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "ONE-GLANCE READ"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "COSMIC / MARKET CONTEXT"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "PORTFOLIO READ"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "STOCK / WATCHLIST LENS"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "LABEL GUIDE"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "Tap for data label meanings"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "activationPrompt("
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "prompt.actionItems"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "prompt.tertiaryActionTitle"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DataSourceIndicator(provenance: summary.provenance"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DataSourceIndicator(provenance: context.provenance"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DataSourceIndicator(provenance: row.provenance"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DATA COVERAGE"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "if !context.metrics.isEmpty"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "numericPortfolioCoverageThreshold = 0.70"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "displayMode == .marketBacked ? portfolioMetrics(for: summary) : []"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "displayMode == .marketBacked ? stockMetrics(for: summary) : []"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "summary.includedPortfolioWeight >= numericPortfolioCoverageThreshold ? .marketBacked : .partialContext"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "displayMode == .marketBacked ? marketMetrics(for: eventSummary) : []"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Coverage must reach 70% before headline return metrics appear."
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "At least 50% coverage is required before portfolio context appears."
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Today stays in cosmic or unavailable mode until provider-backed history clears"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Market weather"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Correlation does not imply causation"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Provider-backed market and historical datasets unavailable"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayMarketContext"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "marketBlock(summary.marketContext, promotedAction: summary.primaryAction)"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "MARKET WEATHER"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "MarketStatusIndicator(showDetails: false"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "marketWeatherCosmosSection"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "MarketWeatherService.shared.loadSummary"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "MARKET WEATHER"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "DataSourceIndicator(provenance: summaryProvenance"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Partial portfolio coverage stays context-only below seventy percent"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "No portfolio stays setup-only with no numeric portfolio metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Below fifty percent portfolio coverage blocks Today portfolio context metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Exactly seventy percent portfolio coverage can render Today portfolio metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Today data coverage distinguishes stale, partial, and unavailable datasets"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Sample and unavailable stock context cannot produce numeric metrics"
require_absent "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Double.random"
require_absent "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "generateMock"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "final class MarketWeatherService"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "SPY"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "QQQ"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "DIA"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "IWM"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "requiredCoverageForNumericClaims = 1.0"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "static let sectorSymbols"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "XLK"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "XLRE"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "XLC"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "requiredSectorCoverageForNumericClaims = 1.0"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "sectorBreadthSummary"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "Full sector coverage is required before sector metrics appear"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "sourceProvenance.isCachedStale"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "displayMode: .marketBackedResult"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "Historical market context only. Correlation does not imply causation"
require_absent "Cosmo Trader/Services/MarketWeatherService.swift" "Double.random"
require_absent "Cosmo Trader/Services/MarketWeatherService.swift" "MockStockData"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayMarketSectorBreadth"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "SECTOR BREADTH"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "sectorBreadthCosmosPanel"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Live market datasets produce source-labeled market weather metrics"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Cached stale market datasets do not produce numeric market claims"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Partial historical market datasets do not produce numeric market claims"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Today integration adds Market Weather without bypassing gates"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Full sector coverage produces separate sector breadth metrics"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Partial sector coverage stays separate and hides sector metrics"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Sector breadth cannot bypass V1 market basket gate"

require_present "Cosmo Trader/Services/Import/BrokerScreenshotParser.swift" "costBasisPerShare"
require_present "Cosmo Trader/Services/Import/SchwabWebPositionsParser.swift" "Cost Basis"
require_present "Cosmo Trader/Services/Import/ThinkOrSwimPositionStatementParser.swift" "Trade Price"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "enum PortfolioImportCommitMode"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "static func commitPortfolio("
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "mode: .append"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "mergeDuplicateStocks"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "weightedAverageCost"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "stock.currentPrice = importedOrProviderPrice"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "currentPrice: importedOrProviderPrice"
require_absent "Cosmo Trader/Services/PortfolioImportService.swift" "static func applyImport("
require_absent "Cosmo Trader/Services/PortfolioImportService.swift" "stock.currentPrice = livePrice ?? unitValueFromCSV ?? knownStock.currentPrice"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "#if DEBUG"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "Generate sample CSV for previews and debug-only manual testing"
require_present "Cosmo Trader/Views/ImportPortfolioView.swift" "Try with DEBUG sample data"
require_present "Cosmo Trader/Views/ImportPortfolioView.swift" "Review rows, then append or replace"
require_absent "Cosmo Trader/Views/ImportPortfolioView.swift" "PortfolioImportService.applyImport"
require_present "Cosmo Trader/Views/ScreenshotImportView.swift" "PortfolioImportService.parseScreenshot(image)"
require_present "Cosmo Trader/Views/ScreenshotImportView.swift" "ImportReviewView("
require_present "Cosmo Trader/Views/ScreenshotImportView.swift" "review every parsed row before choosing append or replace"
require_absent "Cosmo Trader/Views/ScreenshotImportView.swift" "PortfolioImportService.applyImport"
require_absent "Cosmo Trader/Views/ScreenshotImportView.swift" "VisionOCRService.shared.extractPortfolio"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "Append to portfolio"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "Replace my portfolio"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "COST BASIS"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "PortfolioImportService.commitPortfolio"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "without quote or market value does not inherit sample price"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Append import combines duplicate symbols with weighted cost basis"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Screenshot parser holdings append through hardened commit flow"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Screenshot parser unknown ticker survives replace without sample price or astrology"

require_present "Cosmo Trader/Models/FinancialDataProvenance.swift" "enum FinancialDataProvenance"
require_present "Cosmo Trader/Services/StockAPIService.swift" "getQuoteWithProvenance"
require_present "Cosmo Trader/Services/StockAPIService.swift" "fetchKeyStatsResult"
require_present "Cosmo Trader/Views/Components/DataSourceIndicator.swift" "var provenance: FinancialDataProvenance?"

require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "struct StockCosmicCorrelationSummary"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "minimumSampleSize"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "provenance.isProviderBacked"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "Correlation does not imply causation"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "CorrelationDatasetStore.shared.dataset"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "historicalPriceProvenance"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "historicalDatasetCompleteness"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "DataSourceIndicator(provenance: viewModel.historicalPriceProvenance"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "Provider-backed history is required before event-window metrics are shown"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "MoonCurveMarker"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "ForEach(curveMoonEvents)"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "RuleMark(x: .value(\"Scrub\""
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "nearestEvent(to: date"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "selectedEventMetricUnavailableText"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "Historical price data unavailable"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "Correlation does not imply causation"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "displayMode == .marketBackedResult"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "struct PortfolioCosmicCorrelationSummary"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "provenance.isProviderBacked"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "includedPortfolioWeight"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "minimumSampleSize"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "CorrelationDatasetStore.shared.datasets"
require_present "Cosmo Trader/Views/Components/PortfolioCosmicCorrelationView.swift" "DataSourceIndicator(provenance: viewModel.historicalPriceProvenance"
require_present "Cosmo Trader/Views/Components/PortfolioCosmicCorrelationView.swift" "displayMode == .marketBackedResult"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "PortfolioCosmicCorrelationView"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio correlation is weighted by market value"
require_present "Cosmo TraderTests/Services/AstroCorrelationServiceTests.swift" "Historical dataset with empty candles is insufficient and unusable for chart claims"
require_present "Cosmo TraderTests/Services/AstroCorrelationServiceTests.swift" "Stale cached candles remain provider-backed but are labeled stale"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "Overlay event feed includes chart marker kinds with visible icon metadata"
require_present "Cosmo TraderTests/Services/ProductionMockGuardTests.swift" "Sample historical provenance cannot produce chart correlation metrics"
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "Chart and astro overlay copy snippets stay compliance safe"
require_present "Cosmo Trader/Models/HistoricalPriceDataset.swift" "struct HistoricalPriceDataset"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "final class HistoricalPriceCache"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "dataset.provenance.isProviderBacked"
require_present "Cosmo Trader/Services/CorrelationDatasetStore.swift" "final class CorrelationDatasetStore"

require_absent "Cosmo Trader/Models/CosmicEvent.swift" "Consider reducing position sizes"
require_absent "Cosmo Trader/Models/CosmicEvent.swift" "Avoid starting new high-risk positions"
require_absent "Cosmo Trader/Models/CosmicEvent.swift" "Avoid large discretionary purchases"
require_absent "Cosmo Trader/Services/CosmicPatternInterpreter.swift" "consider delaying major decisions"
require_absent "Cosmo Trader/Services/CosmicPatternInterpreter.swift" "using smaller position sizes"
require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "potential contrarian buy signal"
require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "potential contrarian sell signal"
require_absent "Cosmo Trader/Views/Components/CosmicSignalCard.swift" "AVOID"
require_absent "Cosmo Trader/Models/DailyFinancialReading.swift" "Avoid chasing"
require_absent "Cosmo Trader/Models/DailyFinancialReading.swift" "Reduce risk"
require_absent "Cosmo Trader/Models/DailyFinancialReading.swift" "case hold = \"Hold\""
require_absent "Cosmo Trader Widget/SharedWidgetData.swift" "Good for new positions"
require_absent "Cosmo Trader Widget/SharedWidgetData.swift" "Secure your gains"
require_absent "Cosmo Trader Widget/SharedWidgetData.swift" "Trim underperformers"
require_absent "Cosmo Trader Widget/MoonPhaseWidget.swift" "Take Profit"
require_absent "Cosmo Trader Widget/MoonPhaseWidget.swift" "Build Position"
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "Scanner catches known trading-instruction phrases"

if [[ "$failures" -gt 0 ]]; then
  echo "production_mock_guard: failed with $failures issue(s)"
  exit 1
fi

echo "production_mock_guard: passed"
