#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

failures=0

require_absent() {
  local file="$1"
  local needle="$2"
  if grep -Fq -- "$needle" "$ROOT/$file"; then
    echo "FAIL: '$needle' is still present in $file"
    failures=$((failures + 1))
  fi
}

require_present() {
  local file="$1"
  local needle="$2"
  if ! grep -Fq -- "$needle" "$ROOT/$file"; then
    echo "FAIL: '$needle' is missing from $file"
    failures=$((failures + 1))
  fi
}

require_file_absent() {
  local file="$1"
  if [[ -e "$ROOT/$file" ]]; then
    echo "FAIL: legacy file should not exist: $file"
    failures=$((failures + 1))
  fi
}

require_absent "Cosmo Trader/Views/Components/StockChartView.swift" "stock.chartData(for:"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "Historical price data unavailable"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "Key statistics unavailable"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "fetchHistoricalPriceResult"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "HistoricalChartDataQuality.evaluate"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "ChartTimeframe.stockDetailHistoricalCases"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "DataSourceIndicator(provenance: chartProvenance"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "Chart will appear when provider data is available."
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "enum StockChartDisplayMode"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "case candle = \"CANDLE\""
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "enum StockChartCandleEligibility"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "canRenderCandles"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "isCachedStale"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "high > candle.low"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "StockChartModeSelector"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "if effectiveDisplayMode == .candle"
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "RectangleMark("
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "yStart: .value(\"Open\""
require_present "Cosmo Trader/Views/Components/StockChartView.swift" "yEnd: .value(\"Close\""
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "selectedDisplayMode: StockChartDisplayMode"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "if effectiveDisplayMode == .candle"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "curveMoonEvents"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "overlayEvents.filter(\\.isRange)"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "enum ProviderBackedChartFixtureSeeder"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "static let launchFlag = \"--provider-chart-fixture\""
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "arguments.contains(\"--uitesting\") && arguments.contains(launchFlag)"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "UI Test Fixture Provider"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "HistoricalPriceCacheUITestFixtures"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "staleFlag"
require_present "Cosmo Trader/State/AppState.swift" "ProviderBackedChartFixtureSeeder.seedIfRequested"
require_present "Cosmo Trader/State/AppState.swift" "--chart-timeframe="
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "!AppState.usesProviderBackedChartFixture"
require_present "Cosmo TraderTests/Services/HistoricalPriceCacheTests.swift" "Provider-backed chart fixture seeding is unavailable outside explicit UI test mode"
require_present "Cosmo TraderTests/Services/HistoricalPriceCacheTests.swift" "Stale provider-backed chart fixture cannot render candle mode"
require_absent "Cosmo Trader/Views/Components/StockChartView.swift" "ProviderBackedChartFixtureSeeder"
require_absent "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "ProviderBackedChartFixtureSeeder"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "Candle mode requires complete provider backed OHLC candles"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "Candle mode does not synthesize candles from close only data"
require_present "Cosmo TraderTests/Services/ProductionMockGuardTests.swift" "Candle chart mode cannot render sample or synthetic close-only candles"
require_present "Cosmo Trader/Models/HistoricalPriceDataset.swift" "struct HistoricalChartDataQuality"
require_present "Cosmo Trader/Models/HistoricalPriceDataset.swift" "Cached history is stale"
require_present "Cosmo Trader/Models/HistoricalPriceDataset.swift" "canRenderChart: false"
require_present "Cosmo Trader/Models/Stock.swift" "case twoYear = \"2Y\""
require_present "Cosmo Trader/Models/Stock.swift" "static let stockDetailHistoricalCases"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "ASTRO MARKERS"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "chartDataQualityBar"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "visibleLegendKinds"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "canRenderHistoricalChart"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "!historicalPriceProvenance.isCachedStale()"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "stale cached candles cannot render chart context"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "sample chart provenance cannot render production chart context"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "visible legend kinds prioritize moon and Mercury markers"

require_absent "Cosmo Trader/Views/StockDetailView.swift" "generateMockChartData"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "MiniChartView.sampleData"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "formatted52Week"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "stock.formattedMarketCap"
require_present "Cosmo Trader/Views/StockDetailView.swift" "DataSourceIndicator(provenance: priceProvenance"
require_present "Cosmo Trader/Views/StockDetailView.swift" "Fundamentals such as market cap"
require_present "Cosmo Trader/Views/StockDetailView.swift" "StockDetailHistoryActivationViewModel"
require_present "Cosmo Trader/Views/StockDetailView.swift" "stockHistoryActivationCard"
require_present "Cosmo Trader/Views/StockDetailView.swift" "chartReloadToken"
require_present "Cosmo Trader/Views/StockDetailView.swift" "StockDetailViewModel(stock: stock)"
require_present "Cosmo Trader/Views/StockDetailView.swift" "await viewModel.loadTechnicalAnalysis()"
require_present "Cosmo Trader/Views/StockDetailView.swift" "viewModel.loadCosmicPatterns("
require_present "Cosmo Trader/ViewModels/StockDetailViewModel.swift" "func loadTechnicalAnalysis"
require_present "Cosmo Trader/ViewModels/StockDetailViewModel.swift" "func loadCosmicPatterns"
require_present "Cosmo Trader/ViewModels/StockDetailViewModel.swift" "getQuoteWithProvenance"
require_absent "Cosmo Trader/ViewModels/StockDetailViewModel.swift" "Mock"
require_present "Cosmo Trader/ViewModels/StockDetailHistoryActivationViewModel.swift" "HistoricalPriceService.shared.fetchHistoricalPriceResult"
require_present "Cosmo Trader/Services/HistoricalPriceService.swift" "YahooFinanceService.shared.fetchCandles"
require_present "Cosmo Trader/Services/HistoricalPriceService.swift" "providerName: String = FinancialDataProvenance.yahooProvider"
require_absent "Cosmo Trader/Services/HistoricalPriceService.swift" "FinancialDataProvenance.finnhubProvider"
require_present "Cosmo Trader/Models/FinancialDataProvenance.swift" "static let yahooProvider"
require_present "Cosmo TraderTests/Services/HistoricalPriceCacheTests.swift" "Default historical price provider label matches the Yahoo candle source"
require_present "Cosmo Trader/ViewModels/StockDetailHistoryActivationViewModel.swift" "Provider-backed historical prices unavailable"
require_present "Cosmo Trader/ViewModels/StockDetailHistoryActivationViewModel.swift" "Numeric claims remain gated"
require_absent "Cosmo Trader/ViewModels/StockDetailHistoryActivationViewModel.swift" ".sample("
require_absent "Cosmo Trader/ViewModels/StockDetailHistoryActivationViewModel.swift" "Mock"
require_present "Cosmo TraderTests/Services/StockDetailHistoryActivationViewModelTests.swift" "Load action requests provider-backed history"
require_present "Cosmo TraderTests/Services/StockDetailHistoryActivationViewModelTests.swift" "Load action does not create sample data on provider failure"
require_present "Cosmo TraderTests/Services/ProductionMockGuardTests.swift" "Stock detail history activation uses provider service without sample fallback"

require_absent "Cosmo Trader/Services/ChartPatternService.swift" "MockOHLCGenerator.generate"
require_present "Cosmo Trader/Services/ChartPatternService.swift" "pattern analysis unavailable"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "final class StockTechnicalAnalysisService"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "guard dataset.provenance.isProviderBacked"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "guard !dataset.provenance.isCachedStale()"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "guard case .complete = dataset.completeness"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "movingAverage200"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "supportResistance"
require_present "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "Technical lens uses provider-backed historical candles only"
require_absent "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "MockOHLCGenerator"
require_absent "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" "provenance: .sample"
require_absent "Cosmo Trader/Services/StockTechnicalAnalysisService.swift" ".sample(reason:"
require_present "Cosmo Trader/Views/StockDetailView.swift" "technicalAnalysisSection"
require_present "Cosmo Trader/Views/StockDetailView.swift" "StockTechnicalAnalysisView("
require_present "Cosmo Trader/ViewModels/StockDetailViewModel.swift" "fetchHistoricalPriceResult"
require_present "Cosmo Trader/Views/Components/StockTechnicalAnalysisView.swift" "DataSourceIndicator(provenance: summary.provenance"
require_present "Cosmo Trader/Views/Components/StockTechnicalAnalysisView.swift" "Historical technical context only. Not financial advice."
require_present "Cosmo Trader/Views/Components/StockTechnicalAnalysisView.swift" "accessibilityIdentifier(\"stock.technicalAnalysis\")"
require_present "Cosmo Trader/Views/Components/StockTechnicalAnalysisView.swift" "accessibilityIdentifier(\"stock.technicalAnalysis.refreshHistory\")"
require_present "Cosmo TraderTests/Services/StockTechnicalAnalysisServiceTests.swift" "Sample unavailable mixed partial and insufficient data produce no numeric technical claims"
require_present "Cosmo TraderTests/Services/StockTechnicalAnalysisServiceTests.swift" "200D moving average is withheld when fewer than 200 usable candles exist"
require_present "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" "final class StockAstroTechnicalContextService"
require_present "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" "eligibleTechnicalMetrics"
require_present "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" "eligibleCosmicSummary"
require_present "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" "!summary.provenance.isCachedStale()"
require_present "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" "Combined numeric context stays hidden"
require_absent "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" ".sample("
require_absent "Cosmo Trader/Services/StockAstroTechnicalContextService.swift" "Mock"
require_present "Cosmo Trader/Views/Components/StockAstroTechnicalContextView.swift" "labeledIndicator(title: \"TECH\", provenance: context.technicalProvenance"
require_present "Cosmo Trader/Views/Components/StockAstroTechnicalContextView.swift" "labeledIndicator(title: \"COSMIC\", provenance: context.cosmicProvenance"
require_present "Cosmo Trader/Views/Components/StockAstroTechnicalContextView.swift" "DataSourceIndicator(provenance: provenance"
require_present "Cosmo Trader/Views/StockDetailView.swift" "StockAstroTechnicalContextView("
require_present "Cosmo TraderTests/Services/StockAstroTechnicalContextServiceTests.swift" "Combined card renders when technical and cosmic context are provider-backed"
require_present "Cosmo TraderTests/Services/StockAstroTechnicalContextServiceTests.swift" "Mixed provenance does not produce confident combined claims"
require_present "Cosmo TraderTests/Services/StockAstroTechnicalContextServiceTests.swift" "Stale-beyond-policy data does not produce confident combined claims"


require_absent "Cosmo Trader/Services/EarningsService.swift" "generateMockEarningsData"
require_absent "Cosmo Trader/Services/EarningsService.swift" "Double.random"
require_present "Cosmo Trader/Services/EarningsService.swift" "dataProvenance"
require_present "Cosmo Trader/Views/Components/EarningsViews.swift" "DataSourceIndicator(provenance: earningsService.dataProvenance"

require_absent "Cosmo Trader/Views/Components/PortfolioChartView.swift" "generatePortfolioData"
require_absent "Cosmo Trader/Views/Components/PortfolioChartView.swift" "generateBenchmarkData"
require_present "Cosmo Trader/Views/Components/PortfolioChartView.swift" "Portfolio performance history unavailable"

require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "simulateWeeklyReturn"
require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "generateMockHistory"
require_present "Cosmo Trader/Services/CosmicMoodService.swift" "Provider-backed market trend unavailable"
require_present "Cosmo Trader/Services/CosmicMoodService.swift" "minimumMarketCoverageForScore"
# CosmicMoodData must publish enough metadata for consumers to refuse to
# quote a cosmic-only score as a market measurement.
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "enum CosmicMoodDisplayMode"
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "marketDataCoverage"
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "var isMarketBacked"
require_present "Cosmo Trader/Models/CosmicMoodIndex.swift" "Cosmic context only"
# Daily Brief must not leak the partial-astro score as a market reading.
require_present "Cosmo Trader/Services/DailyFinancialReadingService.swift" "cosmic context only"
require_present "Cosmo Trader/Services/DailyFinancialReadingService.swift" "marketBackedScore(from:"
require_present "Cosmo Trader/Services/DailyFinancialReadingService.swift" "marketToneProvenance: mood.provenance"
require_present "Cosmo Trader/Models/DailyFinancialReading.swift" "marketToneProvenance"
require_present "Cosmo Trader/Views/Components/DailyFinancialReadingCockpitView.swift" "marketToneCell"
require_present "Cosmo Trader/Views/Components/DailyFinancialReadingCockpitView.swift" "MARKET TONE (COSMIC)"
# Discover must not quote a cosmic-only mood as a market claim.
require_present "Cosmo Trader/ViewModels/DiscoverViewModel.swift" "mood.isMarketBacked, let value = mood.value"
# Gauge surfaces honest unavailable / cosmic-only states.
require_present "Cosmo Trader/Views/Components/CosmicMoodGauge.swift" "N/A"
require_present "Cosmo Trader/Views/Components/CosmicMoodGauge.swift" "COSMIC ONLY"

require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolioDailyPLProvenance"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "canShowDailyPL"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "canShowDailyPL ? safeUser.formattedDailyChange"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "changeCell(for:"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" ".mixed(reason:"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "struct PortfolioIntelligenceSummary"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "providerQuoteCoverage"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "verifiedAstrologyCoverage"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "historyCoverage >= 0.70"
require_present "Cosmo Trader/ViewModels/PortfolioViewModel.swift" "Unknown-founded holdings stay out of zodiac and element denominators"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "struct PortfolioHistoryCoverageDiagnostics"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "case usable"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "case stale"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "case partial"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "case insufficient"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "case unavailable"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "datasetSnapshot.unavailableProvenanceBySymbol"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "Provider-backed historical prices unavailable"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "isCachedStale"
require_present "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "static func make("
require_absent "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" ".sample("
require_absent "Cosmo Trader/ViewModels/PortfolioHistoryCoverageDiagnostics.swift" "Mock"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "historyCoverageDiagnostics"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "PortfolioHistoryCoverageDiagnostics.make"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "await datasetStore.datasets("
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolioIntelligenceSection"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "PORTFOLIO INTELLIGENCE"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.intelligenceDashboard"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolioHistoryCoverageSection"
# Diagnostics (the stale/partial/insufficient/unavailable count grid) moved
# behind this disclosure in the positions-first reorg; pin the toggle so the
# honest breakdown stays reachable rather than the old always-visible title.
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.historyCoverage.diagnosticsToggle"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "REFRESH HISTORY"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.historyCoverageDiagnostics"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.historyCoverage.refreshHistory"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "await portfolioCorrelationViewModel.load(holdings: holdings, force: true)"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio intelligence distinguishes stored values from provider quote coverage"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio intelligence excludes unknown-founded holdings from zodiac denominator"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio history coverage diagnostics classify usable stale partial insufficient and unavailable holdings"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio history coverage diagnostics do not create fake history for unavailable symbols"
require_absent "Cosmo Trader/Services/PortfolioCompatibilityService.swift" "Consider reducing"
require_absent "Cosmo Trader/Services/PortfolioCompatibilityService.swift" "reduce exposure"
require_present "Cosmo Trader/Views/Components/DataSourceIndicator.swift" "Mixed data"

require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "stocks ?? MockStockData"
require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "FULL MOON: VOLATILITY ELEVATED"
require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "WANING MOON: DE-RISKING WINDOW"
require_absent "Cosmo Trader/Services/CosmicTickerService.swift" "SIGNAL CONFIRMED"
require_present "Cosmo Trader/Services/CosmicTickerService.swift" "MARKET DATA UNAVAILABLE"
# Ticker on Today: stock items only from provider-backed quotes; the
# data-unavailable quips must vanish when live quotes are on the tape.
require_present "Cosmo Trader/Services/CosmicTickerService.swift" "if stocksToShow.isEmpty {"
require_present "Cosmo Trader/ViewModels/CosmicTickerQuotesViewModel.swift" "guard result.provenance.isProviderBacked, let quote = result.quote else {"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "CosmicTickerTape()"
require_present "Cosmo TraderTests/Services/CosmicTickerQuotesTests.swift" "Only provider-backed quotes reach the tape"
require_present "Cosmo TraderTests/Services/CosmicTickerQuotesTests.swift" "unavailable quips vanish"

require_absent "Cosmo Trader/Views/Components/VolumeLeadersView.swift" "from: MockStockData.knownStocks"
require_present "Cosmo Trader/Views/Components/VolumeLeadersView.swift" "Volume leaders unavailable"

require_absent "Cosmo Trader/Services/DailyBriefService.swift" "let knownStocks = Stock.samples + MockStockData.all"
require_absent "Cosmo Trader/Services/DailyBriefService.swift" "for stock in user.portfolio where abs"
require_present "Cosmo Trader/Services/DailyBriefService.swift" "daily highlights must stay empty"

require_file_absent "Cosmo Trader/Views/Tabs/DailyBriefView.swift"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayMarketHoroscopeSummary"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayPortfolioContext"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayStockContext"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayDataCoverage"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayActivationPrompt"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayDataLabelExplainer"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayFirstRunSetupState"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "enum TodayFirstRunSetupAction"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "tertiaryActionTitle"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "primaryAction"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case setupRequired"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case partialContext"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case insufficientCoverage"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case sampleOnly"
require_present "Cosmo Trader/State/AppState.swift" "enum AppNavigationIntent"
require_present "Cosmo Trader/State/AppState.swift" "func requestNavigation"
require_present "Cosmo Trader/State/AppState.swift" "hasSkippedFirstRunDataSetup"
require_present "Cosmo Trader/State/AppState.swift" "skipFirstRunDataSetup"
require_present "Cosmo Trader/State/AppState.swift" "updateFirstRunDataSetupCompletion"
require_present "Cosmo Trader/Views/Onboarding/OnboardingView.swift" "appState.addToWatchlist(stock.symbol)"
require_absent "Cosmo Trader/Views/Onboarding/OnboardingView.swift" "appState.addToPortfolio(stock, shares: 1)"
require_present "Cosmo Trader/Views/Onboarding/OnboardingView.swift" "starter watchlist"
require_present "Cosmo Trader/Views/ContentView.swift" "DailyBriefBackendView()"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "TodayMarketHoroscopeView("
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "setupSkipAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.skipFirstRunDataSetup"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "marketRefreshAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "portfolioSetupAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "portfolioImportAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "watchlistSetupAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "discoverSearchAction:"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.requestNavigation(.portfolioAddHolding)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.requestNavigation(.portfolioImport)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "appState.requestNavigation(.discoverSearch)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "private func loadTodayContext() async"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "private func reloadTodayContext() async"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "firstRunSetupSkipped: appState.hasSkippedFirstRunDataSetup"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "consumeNavigationIntentIfNeeded"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "showImportPortfolio = true"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.empty.importPortfolio"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.empty.addHolding"
require_present "Cosmo Trader/Views/Components/PortfolioImportFeedbackOverlay.swift" "portfolio.importConfirmation"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "PortfolioImportFeedbackOverlay()"
require_present "Cosmo Trader/State/AppState.swift" "struct PortfolioImportFeedback"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "appState.selectedTab = .portfolio"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "appState.portfolioImportFeedback = PortfolioImportFeedback"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "consumeNavigationIntentIfNeeded"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "appState.pendingNavigationIntent == .discoverSearch"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "SearchView()"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "final class TodayMarketHoroscopeViewModel"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "loadPortfolioSummaries"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "loadStockCandidate"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "CorrelationDatasetStore.shared"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "final class TodayMarketHoroscopeComposer"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func compose("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func makeFirstRunSetupState("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func makePortfolioContext("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "func makeStockContext("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "private func makeDataCoverage("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "private func makePrimaryAction("
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "FETCH MARKET HISTORY"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "ADD HOLDING"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Add holding manually"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Import portfolio"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "ADD WATCHLIST SYMBOLS"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Add symbol"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Open Discover/Search"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Provider-backed history is required before Today shows stock-level patterns."
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "enum TodayStockCandidateSource"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "case watchlist"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "source: TodayStockCandidateSource"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "candidates.append((stock, .watchlist))"
require_present "Cosmo Trader/ViewModels/TodayMarketHoroscopeViewModel.swift" "candidates.append((holding, .portfolio))"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "WATCHLIST LENS"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "stockContext.source == .watchlist"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "Search symbols to add to watchlist"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "Search a ticker or swipe right to build a watchlist"
require_present "Cosmo Trader/Views/Tabs/DiscoverView.swift" "Search Symbols"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "Long-press a row to remove from watchlist"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Fetch SPY / QQQ / DIA / IWM history"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Do not create sample market data"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "REFRESH HOLDING HISTORY"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "REFRESH STOCK HISTORY"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Never create sample candles"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "private func dataLabelExplainers()"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.marketHoroscope\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.firstRunDataSetup\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "FIRST-RUN DATA SETUP"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "SKIP SETUP"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.oneGlanceRead\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.activation.\\(accessibilityKey(for: title))\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "ONE-GLANCE READ"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "COSMIC / MARKET CONTEXT"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "PORTFOLIO READ"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "STOCK / WATCHLIST LENS"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "LABEL GUIDE"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "Tap for data label meanings"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "activationPrompt("
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "prompt.actionItems"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "prompt.tertiaryActionTitle"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DataSourceIndicator(provenance: summary.provenance"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DataSourceIndicator(provenance: context.provenance"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DataSourceIndicator(provenance: row.provenance"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "DATA COVERAGE"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "if !context.metrics.isEmpty"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "title.localizedCaseInsensitiveContains(\"refresh\")"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "struct TodayMarketHoroscopeShareCardContent"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "static func make(from summary: TodayMarketHoroscopeSummary)"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "summary.marketContext.metrics"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "summary.portfolioContext.metrics"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "stockContext.metrics"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "Historical context only. No forecast. Not financial advice."
require_present "Cosmo Trader/Views/Social/TodayMarketHoroscopeShareCard.swift" "struct TodayMarketHoroscopeShareCard"
require_present "Cosmo Trader/Views/Social/TodayMarketHoroscopeShareCard.swift" "DataSourceIndicator(provenance: line.provenance"
require_present "Cosmo Trader/Views/Social/TodayMarketHoroscopeShareCard.swift" "DataSourceIndicator(provenance: content.provenance"
require_present "Cosmo Trader/Views/Social/TodayMarketHoroscopeShareCard.swift" "TodayMarketHoroscopeShareCardRenderer"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "accessibilityIdentifier(\"today.marketHoroscope.shareButton\")"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "TodayMarketHoroscopeShareCardRenderer.render(summary: summary)"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "ShareSheet(items: [shareText, shareImage])"
require_absent "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "averageMarketReturn"
require_absent "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "averagePortfolioReturn"
require_absent "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "currentPrice"
require_absent "Cosmo Trader/Models/TodayMarketHoroscopeShareCardContent.swift" "Mock"
require_absent "Cosmo Trader/Views/Social/TodayMarketHoroscopeShareCard.swift" "Mock"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Share card renders unavailable Today state honestly"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Share card numeric claims only come from gated Today metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Share card can render without portfolio or watchlist"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Share card can render with watchlist stock context"
require_present "Cosmo TraderTests/Services/ProductionMockGuardTests.swift" "Today share card does not convert sample or unavailable context into provider-backed claims"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "numericPortfolioCoverageThreshold = 0.70"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "displayMode == .marketBacked ? portfolioMetrics(for: summary) : []"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "displayMode == .marketBacked ? stockMetrics(for: summary) : []"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "summary.includedPortfolioWeight >= numericPortfolioCoverageThreshold ? .marketBacked : .partialContext"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "displayMode == .marketBacked ? marketMetrics(for: eventSummary) : []"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Coverage must reach 70% before headline return metrics appear."
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "At least 50% coverage is required before portfolio context appears."
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Today stays in cosmic or unavailable mode until provider-backed history clears"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Market weather"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Correlation does not imply causation"
require_present "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Provider-backed market and historical datasets unavailable"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayMarketContext"
require_present "Cosmo Trader/Services/NotificationService.swift" "upcomingRetrogradeWindows"
require_present "Cosmo Trader/Services/NotificationService.swift" "MercuryRetrogradeEphemerisProvider"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "marketBlock(summary.marketContext, promotedAction: summary.primaryAction)"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "MARKET WEATHER"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "MarketStatusIndicator(showDetails: false"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "marketWeatherCosmosSection"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "MarketWeatherService.shared.loadSummary"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "MARKET WEATHER"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "DataSourceIndicator(provenance: summaryProvenance"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Partial portfolio coverage stays context-only below seventy percent"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "No portfolio stays setup-only with no numeric portfolio metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Below fifty percent portfolio coverage blocks Today portfolio context metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Holdings without history offer provider-backed history refresh"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Exactly seventy percent portfolio coverage can render Today portfolio metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Today data coverage distinguishes stale, partial, and unavailable datasets"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Sample and unavailable stock context cannot produce numeric metrics"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Watchlist stock context stays unavailable without provider history"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "Today stock candidates prefer watchlist symbols before portfolio holdings"
require_present "Cosmo TraderTests/Services/TodayMarketHoroscopeComposerTests.swift" "AppState watchlist additions persist on the current user path"
require_present "Cosmo TraderTests/Services/FirstRunActivationFunnelSmokeTests.swift" "Today first-run funnel routes to setup without numeric or fake claims"
require_present "Cosmo TraderTests/Services/FirstRunActivationFunnelSmokeTests.swift" "Portfolio import and watchlist setup persist real user data"
require_present "Cosmo TraderTests/Services/FirstRunActivationFunnelSmokeTests.swift" "Provider history load requests real provider candles and does not create sample data"
require_present "Cosmo TraderTests/Services/FirstRunActivationFunnelSmokeTests.swift" "Stock Detail context stays locked on insufficient history"
require_present "Cosmo TraderTests/Services/FirstRunActivationFunnelSmokeTests.swift" "Stock Detail context unlocks only after provider-backed gates pass"
require_present "Cosmo TraderTests/Services/FirstRunActivationFunnelSmokeTests.swift" "First-run funnel copy stays context-only and non-advisory"
require_absent "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "Double.random"
require_absent "Cosmo Trader/Services/TodayMarketHoroscopeComposer.swift" "generateMock"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "final class MarketWeatherService"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "SPY"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "QQQ"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "DIA"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "IWM"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "requiredCoverageForNumericClaims = 1.0"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "static let sectorSymbols"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "XLK"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "XLRE"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "XLC"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "requiredSectorCoverageForNumericClaims = 1.0"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "sectorBreadthSummary"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "Full sector coverage is required before sector metrics appear"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "sourceProvenance.isCachedStale"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "displayMode: .marketBackedResult"
require_present "Cosmo Trader/Services/MarketWeatherService.swift" "Historical market context only. Correlation does not imply causation"
require_absent "Cosmo Trader/Services/MarketWeatherService.swift" "Double.random"
require_absent "Cosmo Trader/Services/MarketWeatherService.swift" "MockStockData"
require_present "Cosmo Trader/Models/TodayMarketHoroscopeSummary.swift" "struct TodayMarketSectorBreadth"
require_present "Cosmo Trader/Views/Components/TodayMarketHoroscopeView.swift" "SECTOR BREADTH"
require_present "Cosmo Trader/Views/Tabs/CosmosView.swift" "sectorBreadthCosmosPanel"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Live market datasets produce source-labeled market weather metrics"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Cached stale market datasets do not produce numeric market claims"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Partial historical market datasets do not produce numeric market claims"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Today integration adds Market Weather without bypassing gates"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Full sector coverage produces separate sector breadth metrics"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Partial sector coverage stays separate and hides sector metrics"
require_present "Cosmo TraderTests/Services/MarketWeatherServiceTests.swift" "Sector breadth cannot bypass V1 market basket gate"

require_present "Cosmo Trader/Services/Import/BrokerScreenshotParser.swift" "costBasisPerShare"
require_present "Cosmo Trader/Services/Import/SchwabWebPositionsParser.swift" "Cost Basis"
require_present "Cosmo Trader/Services/Import/ThinkOrSwimPositionStatementParser.swift" "Trade Price"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "enum PortfolioImportCommitMode"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "static func commitPortfolio("
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "mode: .append"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "mergeDuplicateStocks"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "weightedAverageCost"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "stock.currentPrice = importedOrProviderPrice"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "currentPrice: importedOrProviderPrice"
require_absent "Cosmo Trader/Services/PortfolioImportService.swift" "static func applyImport("
require_absent "Cosmo Trader/Services/PortfolioImportService.swift" "stock.currentPrice = livePrice ?? unitValueFromCSV ?? knownStock.currentPrice"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "#if DEBUG"
require_present "Cosmo Trader/Services/PortfolioImportService.swift" "Generate sample CSV for previews and debug-only manual testing"
require_present "Cosmo Trader/Views/ImportPortfolioView.swift" "Try with DEBUG sample data"
require_present "Cosmo Trader/Views/ImportPortfolioView.swift" "Review rows, then append or replace"
require_absent "Cosmo Trader/Views/ImportPortfolioView.swift" "PortfolioImportService.applyImport"
require_present "Cosmo Trader/Views/ScreenshotImportView.swift" "PortfolioImportService.parseScreenshot(image)"
require_present "Cosmo Trader/Views/ScreenshotImportView.swift" "ImportReviewView("
require_present "Cosmo Trader/Views/ScreenshotImportView.swift" "review every parsed row before choosing append or replace"
require_absent "Cosmo Trader/Views/ScreenshotImportView.swift" "PortfolioImportService.applyImport"
require_absent "Cosmo Trader/Views/ScreenshotImportView.swift" "VisionOCRService.shared.extractPortfolio"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "Append to portfolio"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "Replace my portfolio"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "importReview.commitModeGuide"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "Append keeps current holdings and merges matching symbols"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "COST BASIS"
require_present "Cosmo Trader/Views/Settings/ImportReviewView.swift" "PortfolioImportService.commitPortfolio"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "without quote or market value does not inherit sample price"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Append import combines duplicate symbols with weighted cost basis"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Import success routes to Portfolio with confirmation"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Relaunch load restores imported holdings"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Screenshot parser holdings append through hardened commit flow"
require_present "Cosmo TraderTests/Services/PortfolioImportCommitTests.swift" "Screenshot parser unknown ticker survives replace without sample price or astrology"

require_present "Cosmo Trader/Models/FinancialDataProvenance.swift" "enum FinancialDataProvenance"
require_present "Cosmo Trader/Services/StockAPIService.swift" "getQuoteWithProvenance"
require_present "Cosmo Trader/Services/StockAPIService.swift" "fetchKeyStatsResult"
require_present "Cosmo Trader/Views/Components/DataSourceIndicator.swift" "var provenance: FinancialDataProvenance?"

require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "struct StockCosmicCorrelationSummary"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "minimumSampleSize"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "provenance.isProviderBacked"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "Correlation does not imply causation"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "bestHistoricalReturn"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "weakestHistoricalReturn"
require_present "Cosmo Trader/Services/AstroCorrelationService.swift" "dataCompleteness"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "CorrelationDatasetStore.shared.dataset"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "historicalPriceProvenance"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "historicalDatasetCompleteness"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "shouldShowHistoryActivation"
require_present "Cosmo Trader/ViewModels/HistoricalAstroChartViewModel.swift" "Refresh checks provider-backed history without creating sample candles"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "DataSourceIndicator(provenance: viewModel.historicalPriceProvenance"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "stockDetail.loadProviderHistory"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "Provider-backed history is required before event-window metrics are shown"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "MoonCurveMarker"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "ForEach(curveMoonEvents)"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "RuleMark(x: .value(\"Scrub\""
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "nearestEvent(to: date"
require_present "Cosmo Trader/Views/Components/HistoricalAstroChartView.swift" "selectedEventMetricUnavailableText"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "Historical price data unavailable"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "Correlation does not imply causation"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "displayMode == .marketBackedResult"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "HOW THIS WAS CALCULATED"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "distributionContext"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "WHY NO METRICS"
require_present "Cosmo Trader/Views/Components/AstroCorrelationSummaryView.swift" "not predictive and not financial advice"
require_present "Cosmo TraderTests/Services/AstroCorrelationServiceTests.swift" "Stock summaries expose explainability fields for market-backed results"
require_present "Cosmo TraderTests/Services/AstroCorrelationServiceTests.swift" "Correlation explainability disclosure view instantiates"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "struct PortfolioCosmicCorrelationSummary"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "provenance.isProviderBacked"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "includedPortfolioWeight"
require_present "Cosmo Trader/Services/PortfolioCosmicCorrelationService.swift" "minimumSampleSize"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "struct PortfolioHistorySymbolStatus"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "providerBackedHistoryWeight"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "datasetStore.datasets"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "func reload(holdings:"
require_present "Cosmo Trader/ViewModels/PortfolioCorrelationViewModel.swift" "makeHistoryStatuses"
require_present "Cosmo Trader/Views/Components/PortfolioCosmicCorrelationView.swift" "DataSourceIndicator(provenance: viewModel.historicalPriceProvenance"
require_present "Cosmo Trader/Views/Components/PortfolioCosmicCorrelationView.swift" "displayMode == .marketBackedResult"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "PortfolioCosmicCorrelationView"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolio.loadProviderHistory"
# The duplicate HISTORY STATUS list was merged into the coverage section in
# the positions-first reorg; the surviving per-holding list carries the same
# provenance invariant via this row helper.
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "portfolioHistoryCoverageRow"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "await portfolioCorrelationViewModel.reload(holdings: holdings)"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio correlation is weighted by market value"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio history reload requests provider-backed history and updates coverage"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Portfolio history status uses provider datasets without sample candles"
require_present "Cosmo TraderTests/Services/PortfolioCosmicCorrelationServiceTests.swift" "Stock detail history activation distinguishes unavailable stale and insufficient states"
require_present "Cosmo TraderTests/Services/AstroCorrelationServiceTests.swift" "Historical dataset with empty candles is insufficient and unusable for chart claims"
require_present "Cosmo TraderTests/Services/AstroCorrelationServiceTests.swift" "Stale cached candles remain provider-backed but are labeled stale"
require_present "Cosmo TraderTests/Services/AstroOverlayEventServiceTests.swift" "Overlay event feed includes chart marker kinds with visible icon metadata"
require_present "Cosmo TraderTests/Services/ProductionMockGuardTests.swift" "Sample historical provenance cannot produce chart correlation metrics"
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "Chart and astro overlay copy snippets stay compliance safe"
require_present "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" "AstroOverlayEventService.shared.events"
require_present "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" "Company-specific events unavailable until verified founding metadata exists"
require_present "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" "No market or return claims"
require_present "Cosmo Trader/Views/Components/StockUpcomingCosmicEventsView.swift" "UPCOMING COSMIC EVENTS"
require_present "Cosmo Trader/Views/StockDetailView.swift" "StockUpcomingCosmicEventsView"
require_present "Cosmo TraderTests/Services/StockUpcomingCosmicEventsServiceTests.swift" "Unknown-founded stocks still show broad cosmic events"
require_present "Cosmo TraderTests/Services/StockUpcomingCosmicEventsServiceTests.swift" "Section renders without price or history data"
require_present "Cosmo TraderTests/Services/ProductionMockGuardTests.swift" "Upcoming cosmic events do not use fake price or company metadata"
require_absent "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" "currentPrice"
require_absent "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" "fetchHistoricalPrice"
require_absent "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" "Mock"
require_absent "Cosmo Trader/Services/StockUpcomingCosmicEventsService.swift" ".sample("
require_present "Cosmo Trader/Models/HistoricalPriceDataset.swift" "struct HistoricalPriceDataset"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "final class HistoricalPriceCache"
require_present "Cosmo Trader/Services/HistoricalPriceCache.swift" "dataset.provenance.isProviderBacked"
require_present "Cosmo Trader/Services/CorrelationDatasetStore.swift" "final class CorrelationDatasetStore"

require_absent "Cosmo Trader/Models/CosmicEvent.swift" "Consider reducing position sizes"
require_absent "Cosmo Trader/Models/CosmicEvent.swift" "Avoid starting new high-risk positions"
require_absent "Cosmo Trader/Models/CosmicEvent.swift" "Avoid large discretionary purchases"
require_absent "Cosmo Trader/Services/CosmicPatternInterpreter.swift" "consider delaying major decisions"
require_absent "Cosmo Trader/Services/CosmicPatternInterpreter.swift" "using smaller position sizes"
require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "potential contrarian buy signal"
require_absent "Cosmo Trader/Services/CosmicMoodService.swift" "potential contrarian sell signal"
require_absent "Cosmo Trader/Views/Components/CosmicSignalCard.swift" "AVOID"
require_absent "Cosmo Trader/Models/DailyFinancialReading.swift" "Avoid chasing"
require_absent "Cosmo Trader/Models/DailyFinancialReading.swift" "Reduce risk"
require_absent "Cosmo Trader/Models/DailyFinancialReading.swift" "case hold = \"Hold\""
require_absent "Cosmo Trader Widget/SharedWidgetData.swift" "Good for new positions"
require_absent "Cosmo Trader Widget/SharedWidgetData.swift" "Secure your gains"
require_absent "Cosmo Trader Widget/SharedWidgetData.swift" "Trim underperformers"
require_absent "Cosmo Trader Widget/MoonPhaseWidget.swift" "Take Profit"
require_absent "Cosmo Trader Widget/MoonPhaseWidget.swift" "Build Position"
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "Scanner catches known trading-instruction phrases"

# Prediction ledger integrity (specs/prediction-ledger-mvp.md): only
# market-backed summaries may become scored predictions, recorded claims are
# immutable (an outcome is set exactly once, nothing else changes), and
# after-close records are flagged so they can never predict the past.
require_present "Cosmo Trader/Services/PredictionExtractor.swift" "guard event.displayMode == .marketBackedResult,"
require_present "Cosmo Trader/Services/PredictionExtractor.swift" "guard summary.displayMode == .marketBackedResult,"
require_present "Cosmo Trader/Services/PredictionLedgerStore.swift" "records[recordIndex].claims[claimIndex].outcome == nil else {"
require_present "Cosmo Trader/Services/PredictionLedgerStore.swift" "guard records[existingIndex].isNoCall, !record.isNoCall else {"
require_present "Cosmo Trader/Models/PredictionLedger.swift" "let recordedAfterClose: Bool"
require_present "Cosmo TraderTests/Services/PredictionExtractorTests.swift" "Non-market-backed weather summaries never create claims"
require_present "Cosmo TraderTests/Services/PredictionLedgerStoreTests.swift" "Outcome applies exactly once and alters nothing else"

# Prediction scoring (phase B): outcomes come only from provider-backed
# candles, absent data resolves unresolved instead of guessing, and accuracy
# stats exclude pushes and after-close records.
require_present "Cosmo Trader/Services/PredictionScoringService.swift" "if dataset.provenance.isProviderBacked {"
require_present "Cosmo Trader/Services/PredictionScoringService.swift" "static let flatDeadbandPercent = 0.10"
require_present "Cosmo Trader/Services/PredictionScoringService.swift" "static let minimumPortfolioWeightCoverage = 0.70"
require_present "Cosmo Trader/Services/PredictionScoringService.swift" "let weights = claim.portfolioWeights ?? [:]"
require_present "Cosmo Trader/Models/PredictionScorecard.swift" ".filter { !\$0.recordedAfterClose }"
require_present "Cosmo TraderTests/Services/PredictionScoringServiceTests.swift" "Sample-provenance datasets are treated as unavailable, never scored"
require_present "Cosmo TraderTests/Services/PredictionScorecardTests.swift" "After-close records never enter accuracy stats"

# Prediction ledger surfaces (phase C): the scorecard card renders on Today
# with provenance indicators and compliance-gated copy; abstain and
# after-close states render honestly.
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "TodayPredictionCard(viewModel: predictionLedgerViewModel)"
require_present "Cosmo Trader/Views/Settings/DailyBriefBackendView.swift" "await predictionLedgerViewModel.load()"
require_present "Cosmo Trader/Views/Components/TodayPredictionCard.swift" "DataSourceIndicator(provenance: viewModel.scorecard.provenance"
require_present "Cosmo Trader/Views/Components/TodayPredictionCard.swift" "The cosmos abstained today."
require_present "Cosmo Trader/Views/Components/TodayPredictionCard.swift" "not predictive and not financial advice"
require_present "Cosmo Trader/Views/Today/CosmicScorecardView.swift" "COIN FLIP BASELINE: 50%"
require_present "Cosmo Trader/Views/Today/CosmicScorecardView.swift" "AFTER CLOSE — NOT SCORED"
require_present "Cosmo Trader/Views/Today/CosmicScorecardView.swift" "Correlation does not imply causation"
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "Cosmic scorecard copy snippets stay compliance safe"

# Manual holdings editing: adds go through the shares editor (no hardcoded
# 1-share adds), cost basis is user-entered or honestly absent (nil), and
# validation stays in the testable HoldingSharesInput rules.
require_present "Cosmo Trader/Views/Components/HoldingSharesEditor.swift" "static func parseShares"
require_present "Cosmo Trader/Views/Components/HoldingSharesEditor.swift" "case unknown"
require_present "Cosmo Trader/State/AppState.swift" "func updateHolding(symbol: String, shares: Double, costBasisPerShare: Double?)"
require_absent "Cosmo Trader/Views/StockDetailView.swift" "shares: 1)"
require_present "Cosmo Trader/Views/StockDetailView.swift" "HoldingSharesEditorView("
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "HoldingSharesEditorView("
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "Shares editor copy snippets stay compliance safe"

# All-time P/L: both legs must be honest — cost basis is user/import data
# (excluded when absent, never guessed) and the current leg needs a
# provider-backed quote. Partial coverage is labeled, and the old Profile
# placeholder stays deleted.
require_present "Cosmo Trader/Models/PortfolioAllTimePLSummary.swift" "quoteProvenance.isProviderBacked"
require_present "Cosmo Trader/Models/PortfolioAllTimePLSummary.swift" "missingCostBasisSymbols"
require_present "Cosmo Trader/Views/Components/PortfolioAllTimePLRow.swift" "summary.coverageLabel"
require_present "Cosmo Trader/Views/Tabs/PortfolioView.swift" "PortfolioAllTimePLRow(summary: allTimePLSummary)"
require_present "Cosmo Trader/Views/Components/StockPositionSummaryView.swift" "priceProvenance.isProviderBacked"
require_present "Cosmo Trader/Views/StockDetailView.swift" "StockPositionSummaryView("
require_absent "Cosmo Trader/ViewModels/ProfileViewModel.swift" "allTimeGainLoss"
require_present "Cosmo TraderTests/Services/ComplianceCopyGuardTests.swift" "All-time P/L copy snippets stay compliance safe"

# Cloud profile pull must never delete local data: the launch-time fetch
# merges through CloudProfileMerge (fill-when-empty only). The pre-fix
# blind replace wiped on-device portfolios when the backend was behind.
require_present "Cosmo Trader/State/AppState.swift" "CloudProfileMerge.merge("
require_absent "Cosmo Trader/State/AppState.swift" "localUser.portfolio = cloudPortfolio"
require_present "Cosmo Trader/Services/CloudProfileMerge.swift" "never"

# Finnhub key delivery: the app calls Finnhub directly from the client, so
# its key ships in the bundled Secrets.plist and CosmoConfig must read that
# resource (GENERATE_INFOPLIST_FILE drops custom Info.plist keys, so the
# xcconfig value cannot reach Info.plist). Without this read,
# isFinnhubConfigured is false in every build and all quotes (daily/all-time
# P/L, portfolio) go dark. The Release secret scanner allows Secrets.plist
# only when it carries client-safe keys.
require_present "Cosmo Trader/Configuration/CosmoConfig.swift" "valueFromBundledSecretsPlist"
require_present "Cosmo Trader/Configuration/CosmoConfig.swift" "forResource: \"Secrets\", withExtension: \"plist\""
require_present "Scripts/verify_no_secrets.sh" "check_bundled_secrets_plist"
require_present "Scripts/verify_no_secrets.sh" "carries non-allowlisted key"

if [[ "$failures" -gt 0 ]]; then
  echo "production_mock_guard: failed with $failures issue(s)"
  exit 1
fi

echo "production_mock_guard: passed"
